### ISSUE TITLE
Bil installation fails

### ISSUE THREAD

**Issue by kritixilithos** [fergusq/bils#1]
I cloned this repository and tried to install the `plot_ascii` bil using bilar as stated in the README. `bilar compress` resulted in a successful package creation (with some errors), however `bilar install` failed. The error is shown below.

```
$ bilar compress plot_ascii/
>>> tar --create --xz --file plot_ascii.1.0.2.bil.tar.xz plot_ascii --transform s/plot_ascii/plot_ascii.1.0.2.bil/
tar: --transform: Cannot stat: No such file or directory
tar: s/plot_ascii/plot_ascii.1.0.2.bil: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
Package successfully created.
$ bilar install plot_ascii.1.0.2.bil.tar.xz
>>> tar --extract --xz --file plot_ascii.1.0.2.bil.tar.xz -C /Users/#######/.bilar/installed plot_ascii.1.0.2.bil
tar: plot_ascii.1.0.2.bil: Not found in archive
tar: Error exit delayed from previous errors.
Bil file 'plot_ascii.1.0.2.bil.tar.xz' is not valid (invalid directory structure or package file).
Installation failed.
```

**Comment by fergusq** [comment]
This problem arises because your tar does not support the `--transform` option. This causes the resulting package file to be invalid, which bilar notices and refuses to continue installation.

As the bug is related to the Bilar system and not this exact bil, this issue should probably be opened on the bilar repository issues page. Can you post it there?
